#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
# Configure HAproxy to send traffic to web-01 & web-02
# Use roundrobin algorithm for distribution

apt-get -y update
apt-get -y install haproxy

printf %s "
backend web-servers
        balance roundrobin
        option forwardfor
        server 200459-web-01 100.25.212.192:80 check
        server 200459-web-02 54.236.51.221:80 check
frontend haproxy_balancer
         bind *:80
         mode http
         default_backend web-servers
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
